name: newsy
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  flashy_tab_bar2: ^0.0.6
  floating_frosted_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  get: 4.6.5
  http: ^0.13.5
  intl: ^0.18.0
  motion_tab_bar_v2: ^0.2.6

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/pngs/"
    - "assets/images/pngs/country_flags/"
