class ImagePaths {
  static const pngsPath = "assets/images/pngs";
  static const appLogoImagePath = "$pngsPath/newsy.png";
}

class CountryFlagPaths {
  static const countryFlagsPath = "assets/images/pngs/country_flags";

  static Map<String, String> countryFlags = {
    "United Arab Emirates": "$countryFlagsPath/united_arab_emirates.png",
    "Argentina": "$countryFlagsPath/argentina.png",
    "Austria": "$countryFlagsPath/austria.png",
    "Australia": "$countryFlagsPath/australia.png",
    "Belgium": "$countryFlagsPath/belgium.png",
    "Bulgaria": "$countryFlagsPath/bulgaria.png",
    "Brazil": "$countryFlagsPath/brazil.png",
    "Canada": "$countryFlagsPath/canada.png",
    "Switzerland": "$countryFlagsPath/switzerland.png",
    "China": "$countryFlagsPath/china.png",
    "Colombia": "$countryFlagsPath/colombia.png",
    "Cuba": "$countryFlagsPath/cuba.png",
    "Czechia": "$countryFlagsPath/czechia.png",
    "Germany": "$countryFlagsPath/germany.png",
    "France": "$countryFlagsPath/france.png",
    "United Kingdom": "$countryFlagsPath/united_kingdom.png",
    "Greece": "$countryFlagsPath/greece.png",
    "Hong Kong": "$countryFlagsPath/hong_kong.png",
    "Hungary": "$countryFlagsPath/hungary.png",
    "Indonesia": "$countryFlagsPath/indonesia.png",
    "Ireland": "$countryFlagsPath/ireland.png",
    "Israel": "$countryFlagsPath/israel.png",
    "India": "$countryFlagsPath/india.png",
    "Italy": "$countryFlagsPath/italy.png",
    "Japan": "$countryFlagsPath/japan.png",
    "South Korea": "$countryFlagsPath/south_korea.png",
    "Lithuania": "$countryFlagsPath/lithuania.png",
    "Latvia": "$countryFlagsPath/latvia.png",
    "Morocco": "$countryFlagsPath/morocco.png",
    "Mexico": "$countryFlagsPath/mexico.png",
    "Malaysia": "$countryFlagsPath/malaysia.png",
    "Nigeria": "$countryFlagsPath/nigeria.png",
    "Netherlands": "$countryFlagsPath/netherlands.png",
    "Algeria": "$countryFlagsPath/algeria.png",
    "New Zealand": "$countryFlagsPath/new_zealand.png",
    "Philippines": "$countryFlagsPath/philippines.png",
    "Poland": "$countryFlagsPath/poland.png",
    "Portugal": "$countryFlagsPath/portugal.png",
    "Romania": "$countryFlagsPath/romania.png",
    "Serbia": "$countryFlagsPath/serbia.png",
    "Russia": "$countryFlagsPath/russia.png",
    "Saudi Arabia": "$countryFlagsPath/saudi_arabia.png",
    "Sweden": "$countryFlagsPath/sweden.png",
    "Singapore": "$countryFlagsPath/singapore.png",
    "Slovenia": "$countryFlagsPath/slovenia.png",
    "Slovakia": "$countryFlagsPath/slovakia.png",
    "Thailand": "$countryFlagsPath/thailand.png",
    "Turkiye": "$countryFlagsPath/turkiye.png",
    "Taiwan": "$countryFlagsPath/taiwan.png",
    "Ukraine": "$countryFlagsPath/ukraine.png",
    "United States": "$countryFlagsPath/united_states.png",
    "Venezuela": "$countryFlagsPath/venezuela.png",
    "South Africa": "$countryFlagsPath/south_africa.png",
  };
}
